name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      binary_path: hello
    steps:
      - uses: actions/checkout@v3
      - name: Compile hello.c
        run: gcc hello.c -o hello

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run test on hello binary
        run: |
          ./hello | grep -q "Hello, World!" && echo "Test passed" || (echo "Test failed" && exit 1)
